### PR TITLE
Update to Rx 5.0

### PR DESCRIPTION
**Pull request by panesofglass**
NOTE: this drops support for `net46`, which is not supported by Rx 5.0.

### CODE REVIEW

**Comment by panesofglass** [comment]
@deviousasti should I merge this? I don't remember why I haven't already.

**Comment by panesofglass** [comment]
Should we include more target frameworks?

**Comment by deviousasti** [comment]
For Rx5, `netstandard2.0` should be sufficient the runtimes of `net472` upto `net48`, and `netstandard2.1` should cover all of .Net Core, the rest is `net5`, so while this isn't unsafe to merge, `paket.lock` still pegs Rx at 4.4.1, and not 5.0. 

```
 System.Reactive (>= 4.4.1) - restriction: || (>= net46) (>= netstandard2.0) (>= uap10.0)
```

We need to probably run a paket update to bring in 5.0, and then removing this would make more sense in a newer release.

**Comment by panesofglass** [comment]
This now also bumps to F# 5.0.

**Comment by panesofglass** [comment]
Good comments. Thanks!

**Review by deviousasti — APPROVED** [review]
LGTM!

**Pull request merged**
