### PR TITLE
Lower requires FSharp.Core and clean out TFMs

### PR DESCRIPTION
**Pull request by cartermp**
Fixes https://github.com/fsprojects/FSharp.Control.Reactive/issues/160 

Also clears out what _appears_ to be redundant TFM usage (it really should not be needed, since there are no conditional defines for each target). and some stuff in the travis build.

### CODE REVIEW

**Comment by cartermp** [comment]
Let's see if my nonsense in the travil file was right or not.

**Comment by cartermp** [comment]
Looks like it  was!

**Comment by deviousasti** [comment]
Hey Philip,

The multiple targets frameworks - IIRC, using this in netstandard 2.0 adds a reference to Tasks Extensions which isn't necessary in net5.0.

**Comment by cartermp** [comment]
According to the docs that's not the case, but I may be looking at the wrong thing: https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskextensions?view=netstandard-2.0

In either case, I'm definitely not married to removing the multiple TFMs. That's just a quick thing I saw and thought wasn't necessary.

**Comment by deviousasti** [comment]
So, System.Reactive also ships versions for netstandard2.0 and net5.0, probably for the same reasons.
Maybe we should align it with their TFMs.

image

**Comment by deviousasti** [comment]
Merged. Thanks @cartermp!

**Comment by panesofglass** [comment]
@deviousasti if you don't mind tagging this, it should automatically deploy the updated packages. An update in the RELEASE_NOTES would be nice, too. Thanks for reviewing and merging!

**Comment by deviousasti** [comment]
@panesofglass Done. Updated the release notes, and tagged 5.0.1. Thanks!

**Comment by deviousasti** [comment]
@panesofglass While `FSharp.Core` was updated in paket.dependencies to >= 4.7.2, we needed to change it in paket.lock for it to take effect.

**Comment by cartermp** [comment]
Hmmm. I did a `paket install` locally but maybe that wasn't picked up in my PR?

**Comment by deviousasti** [comment]
From paket docs:

> Unlike paket update, paket install will only look for new versions of dependencies that have been modified in paket.dependencies and use the version from paket.lock for all other dependencies.

I think it means that since the lock version was already at 5.0.1, it won't downgrade.

**Comment by deviousasti** [comment]
Fixed in #162.

**Pull request merged**
