### PR TITLE
nunit refactor to xunit.

### PR DESCRIPTION
**Pull request by xp44mm**
because xunit is my used lib, maybe some body else need it also.

### CODE REVIEW

**Comment by stijnmoreels** [comment]
I think you forgot to add the `paket.references`/`paket.dependencies` for xUnit?
xUnit is also my preffered testing framework \w FsCheck; but should check with @panesofglass .

Also, if we would move the xUnit; I would make the change complete and also update all the other tests and migrate to xUnit.

**Comment by xp44mm** [comment]
i compile pass the tests in my separate project. and some functionality i can't make sense. that is:
open FSharp.Control.Reactive.Testing.Marbles
Observable.switchMap
Observable.exhaustMap
Observable.catchOption
Observable.catchResult
Observable.consumeMap
Observable.consumeNextOn
Observable.serve
so. i comment them out with whole Fact it belong. let tests pass.

**Comment by xp44mm** [comment]
i have converted all test files. and run the tests is correctly.

**Comment by panesofglass** [comment]
I'm fine switching to xUnit. Do we know why the builds are failing?

**Comment by panesofglass** [comment]
Looks like the builds fail due to incorrect dependency listings: `Package FsCheck.Xunit was not found in group Main of the paket.lock file.`

**Pull request merged**
