### PR TITLE
Update to Rx-3.0

### PR DESCRIPTION
**Pull request by jakelishman**
This updates the project to use the new (v3.0) version of the Reactive Extensions.

Since `System.Reactive` has dropped support for .NET framework 4.0 and Profile259, I have removed them from the solution.  I'm not well experienced in building .NET libraries though, so if there's a way around that, I can rectify the PR.

### CODE REVIEW

**Comment by jakelishman** [comment]
Apologies on the broken build in the middle commit - I missed that there was a nuget target and hadn't udpated the `paket.template` correctly.

**Comment by cloudRoutine** [comment]
don't worry about that, it happens all the time to every repo using CI. in fact that's exactly what we want to happen :wink:

**Comment by cloudRoutine** [comment]
did you try having FSharp.Control.Reactive only depend on Reactive.Core? just curious if you know how much of the surface area that would effect.

**Comment by jakelishman** [comment]
With only `System.Reactive.Core`, there didn't seem to be any static member extensions to the `Observable` type - I believe they're all defined as members on `System.Reactive.Linq.Observable`.  So to answer the question, there's little useful coverage with only `Core`.

**Pull request merged**
