### PR TITLE
Make the repo build properly in Appveyor

### PR DESCRIPTION
**Pull request by marklam**
- Un-complicated the paket references
- Trimmed the frameworks to match those of System.Reactive
- Update the solution file format
- Updated build tools and packages

A successful build in a default appveyor setup is here: https://ci.appveyor.com/project/MarkLambert/fsharp-control-reactive

### CODE REVIEW

**Comment by deviousasti** [comment]
This is great, I'm going to try merging it.

**Comment by deviousasti** [comment]
Some[ build warnings](https://ci.appveyor.com/project/panesofglass/fsharp-control-reactive/builds/50649596) for the generated metaproj.

```
C:\projects\fsharp-control-reactive\tests\FSharp.Control.Reactive.Tests.fsproj.metaproj : warning MSB4078: The project file "tests\FSharp.Control.Reactive.Tests.fsproj" is not supported by MSBuild and cannot be built.
C:\projects\fsharp-control-reactive\src\FSharp.Control.Reactive\FSharp.Control.Reactive.fsproj.metaproj : warning MSB4078: The project file "src\FSharp.Control.Reactive\FSharp.Control.Reactive.fsproj" is not supported by MSBuild and cannot be built.
C:\projects\fsharp-control-reactive\src\FSharp.Control.Reactive.Testing\FSharp.Control.Reactive.Testing.fsproj.metaproj : warning MSB4078: The project file "src\FSharp.Control.Reactive.Testing\FSharp.Control.Reactive.Testing.fsproj" is not supported by MSBuild and cannot be built.
``

**Comment by marklam** [comment]
It looks like something in the build settings isn't the default (it's @panesofglass 's appveyor account that's running it). I'm trying to get the same effect on the build of my fork so I can see what needs to be changed. 

The default 'build what's in appveyor.yml' or 'run build.ps1' both build cleanly for me, so it must be a different build setup I think.

**Comment by deviousasti** [comment]
It's not running `build.ps1`. 
It's straight up calling `msbuild`.
```
msbuild "C:\projects\fsharp-control-reactive\FSharp.Control.Reactive.sln"
```

Another thing is that it's MSBuild `14.0.25420.1` (one that ships with VS) whereas on your's it's ` 17.3.4+a400405ba` (one that ships with .NET SDK).

**Comment by marklam** [comment]
I can reproduce it with the same source on my appveyor:
https://ci.appveyor.com/project/MarkLambert/fsharp-control-reactive/builds/50650111

It looks like you need to have configured the build to ignore appveyor.yml (In the General settings) and run msbuild on FSharp.Control.Reactive.sln (in the Build settings).

(When the appveyor.yml is ignored, the default Environment has "Build worker image: Visual Studio 2019" so I'm not sure why it's running MSBuild 14 (from VS 2015?), but without doing the tool restore I don't think it would work anyway)

I think the short story is that the settings in the appveyor instance need to be tweaked, or maybe build should be moved to a github action. 

There's also still the issue of how to then publish the package to the official nuget feed.

**Comment by deviousasti** [comment]
I don't have access to the CI settings. Maybe we could move it to Github actions.
The Nuget API key must also be on the CI as a secret. I'll need to be a co-owner of the package for it.

**Pull request merged**
