### PR TITLE
Support for Profile259

### PR DESCRIPTION
**Pull request by TheAngryByrd**
This is the initial pull request to address #29 and #54 .  **This is bound to break things**.  One of them being support for .net 4.0  Please test aggressively and provide feedback .

- [x] Convert projects to Profile259
- [ ] Tested on existing apps
- [ ] Tested on iOS
- [ ] Tested on Android
- [ ] Tested on Windows Store Apps
- [ ] Tested on Windows Phone 8.1 Apps

### CODE REVIEW

**Comment by panesofglass** [comment]
:+1: thanks!

**Comment by jlewicki** [comment]
I was wondering if there are any updates on this issue?  

I added profile 259 support in my fork (before noticing this issue), but took a slightly different approach of adding a second .fsproj file specific to profile 259.  The resulting nuget package keeps the existing lib/net40 folder, and adds lib/portable-net45+win+wpa81+blahblahblah.  I though doing it that way would have less of a chance of breaking existing consumers.

Would it be worth creating a separate PR?

**Comment by cloudRoutine** [comment]
@jlewicki  It would, that's the preferable approach

**Comment by cloudRoutine** [comment]
Unnecessary after #74

**Pull request closed without merging**
