### PR TITLE
Update to System.Reactive 4.0

### PR DESCRIPTION
**Pull request by kblohm**
Hi,
i updated to System.Reactive version 4.0 that was just released. To do so, i had to drop net45 as that is not supported anymore.
I also wanted to change some docs, but i could not generate them locally to test.
I always get a 
```unknown(1,1): error FS3216: type 'FSharp.CodeFormat.CodeFormatAgent' not found in assembly 'FSharp.CodeFormat, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. A possible cause may be a version incompatibility. You may need to explicitly reference the correct version of this assembly to allow all referenced components to use the correct version.``` 
I tried some stuff (updating to newer versions of FSF for example) but i did not manage to fix that :/.

### CODE REVIEW

**Comment by panesofglass** [comment]
No worries on the docs. Thanks for your PR. Docs have been broken for some time, unfortunately.

**Comment by panesofglass** [comment]
I think the `App.config` can also go away in the tests project.

**Comment by kblohm** [comment]
I removed the `App.config`. But i would like to keep `net46`. I think supporting the same frameworks System.Reactive supports is a good idea in general (although uap is missing here). 
FAKE also needs `net46` for the legacy stuff :).

**Comment by panesofglass** [comment]
Thanks!

**Comment by panesofglass** [comment]
I'll work on getting this packaged and shipped.

**Pull request merged**
