### PR TITLE
Add experimental support for NetStandard

### PR DESCRIPTION
**Pull request by TOTBWF**
System.Reactive already supports netstandard, so this PR updates the build files to both include netstandard as a target, as well as migrating them to the new, pared down fsproj format.

### CODE REVIEW

**Comment by TOTBWF** [comment]
This PR does require MSBuild 15 to compile, which explains why the CI checks are failing, as they use MsBuild 14 and Xbuild 14 (Which is now deprecated)

**Comment by panesofglass** [comment]
I think the MSBuild 15 issue can be resolved by modifying the `appveyor.yml` and `.travis.yml` files. Care to take a crack at it?

**Comment by panesofglass** [comment]
Looks like a few tests are failing on AppVeyor. Also, please either remove SourceLink or update to the new version that works with .NET Core.

**Comment by panesofglass** [comment]
@cloudRoutine it looks as though the config on AppVeyor is causing this to break. It's trying to run `build.cmd NuGet`, which we replaced with `build.cmd Pack` in `appveyor.yml`.

**Comment by panesofglass** [comment]
@forki do you know why I would see a build error stating, 'Target "NuGet" is not defined.' when I don't have a "NuGet" target?

**Comment by panesofglass** [comment]
@TOTBWF I just submitted another PR to fix the build. Can you try merging?

**Comment by TOTBWF** [comment]
Looks like the AppVeyor build is just broken on the pack stage, all the tests pass.

**Comment by panesofglass** [comment]
@enricosada, we are really close on this. Any chance you could help us figure out what's wrong with `pack`?

**Comment by dsyme** [comment]
cc @ChrSteinert  too, who is a magician in this knid of work :)

**Comment by enricosada** [comment]
Let me check

**Comment by ChrSteinert** [comment]
Seems to be a lot of love has been put into this already! :)
I'll see if I can be of any help…

**Comment by ChrSteinert** [comment]
Is there a specific reason, why the packaging is done via dotnet CLI and not Paket?
I got it working locally with Paket …

**Comment by ChrSteinert** [comment]
I guess this should do it 👍

**Comment by enricosada** [comment]
@ChrSteinert the `dotnet pack` should work with paket too (and is the preferred way with .net core sdk).

i tried and i think the issues is `<IncludeSymbols>true</IncludeSymbols>`, that is used to generate another package (`.symbols.nuget`), but paket target has a bug with that.
I'll open and issue in paket repo. meanwhile i'll send a PR to fix this here

**Comment by enricosada** [comment]
paket bug is https://github.com/fsprojects/Paket/issues/2689

**Pull request merged**
