### PR TITLE
Fix docs and update to FAKE 5

### PR DESCRIPTION
**Pull request by kblohm**
Hi,
in #107 you told me that the docs were broken for some time now, so i thought i might fix that.
At least for me (on windows) they build just fine now.
While i was at it i also updated the build to use FAKE 5.
Some stuff that might still need some work:
* I did not test the release targets as they require git permissions.
* `build.sh` might need some more work, i am not very firm in bash-scripts :/.
* `.travis.yml` and `appveyor.yml` might not be quite right

### CODE REVIEW

**Comment by kblohm** [comment]
Any ideas why travis is not working?

**Comment by panesofglass** [comment]
I'll try on my Ubuntu subsystem later today. Thanks for doing this!

**Comment by kblohm** [comment]
Soo.. that travis problem was apparently a bug in the dotnet tooling and how they try to resolve dotnet sdk tools that are installed to a none default folder. So i changed the way to bootstrap FAKE from the global tool to a `build.proj` file.
I also added a `HostDocs` target to host the docs with AspNetCore, so we dont need to generate the docs with a different root just for testing.

**Comment by kblohm** [comment]
At least this is a new error now :/ can someone have a look? Not sure why there are no permissions to run the script. Not being able to test this locally makes this kind of hard.

**Comment by panesofglass** [comment]
I merged and added a few clean up commits. I think I broke the `HostDocs`, but it fixes the paths for the published docs. I am not sure the best way to resolve using local or fixed paths.

**Comment by kblohm** [comment]
Mh, i was pretty sure gh-pages are fine with relative paths :/.

**Comment by panesofglass** [comment]
In any case, you fixed the documentation generation, and it's now updated! Thanks!

**Comment by panesofglass** [comment]
Also, @kblohm, apologies for not cleanly merging, leading this to appear unmerged.

**Pull request closed without merging**
