### PR TITLE
Reactive Marble Proposal

### PR DESCRIPTION
**Pull request by stijnmoreels**
This commit contains a proposal for an alternate way to test reactive
functions.
It introduces a `Marbles` module to create from string-representations a
sequence of recorded test notifications that can be used as input for a
Hot or Cold observable.

I'm planning to add some documentation about this; but for now the
included tests could do.

This is just a working version, there's a lot room for improvement.

Thanks!

### CODE REVIEW

**Comment by panesofglass** [comment]
I like it! Is it ready to merge? Also, would you be interested in becoming a maintainer? Thank you for all your recent contributions!

**Comment by stijnmoreels** [comment]
1. For me it's ready to merge. Wasn't quite sure that it would be appreciated/approved. It's basically inspired by many other Rx implementations, and it could be useful to testing both basic scenarios to learn reactive extensions, but also to test race conditions easily.

2. I would love that! Just not sure what's my responsibility would be as maintainer?

3. You're very welcome! I'm looking for ways to make this library more than "just" wrappers for the existing package, so it could be more frequently used in real projects.

**Comment by panesofglass** [comment]
@dsyme could you add @stijnmoreels as an admin for this project, please?

**Comment by sergey-tihon** [comment]
@panesofglass I've send invitation to @stijnmoreels

**Comment by panesofglass** [comment]
@sergey-tihon thank you!

**Pull request merged**
